---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates RDS Aurora single database server (if selected)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Database Parameters
      Parameters:
        - DatabaseInstanceType
        - DatabaseMasterUsername
        - DatabaseMasterPassword
        - DatabaseName
        - DatabaseAllocatedStorage
        - DatabaseSecurityGroup
        - DataSubnet0
        - DataSubnet1
        - DataSubnet2
        - MultiAZDatabase
    ParameterLabels:
      DatabaseInstanceType:
        default: DB Instance Class
      DatabaseMasterUsername:
        default: DB Master Username
      DatabaseMasterPassword:
        default: DB Master Password
      DatabaseName:
        default: DB Name
      DatabaseAllocatedStorage:
        default: DB disk size
      DatabaseSecurityGroup:
        default: DB Security Group
      DataSubnet0:
        default: Data Subnet for AZ 0
      DataSubnet1:
        default: Data Subnet for AZ 1
      DataSubnet2:
        default: Data Subnet for AZ 2
      MultiAZDatabase:
        default: Create a multi-AZ instance?

Parameters:

  DatabaseInstanceType:
    AllowedValues:
      - db.t3.small
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
    ConstraintDescription: Must be a valid RDS instance class.
    Default: db.t3.medium
    Description: The Amazon RDS database instance class.
    Type: String
  DatabaseMasterUsername:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The Amazon RDS master username.
    ConstraintDescription: Must contain only alphanumeric characters and be at least 8 characters.
    MaxLength: 16
    MinLength: 1
    Type: String
  DatabaseMasterPassword:
    AllowedPattern: ^([a-z0-9A-Z`~!#$%^&*()_+,\\-])*$
    ConstraintDescription: Must be letters (upper or lower), numbers, and these special characters '_'`~!#$%^&*()_+,-    
    Description: The Amazon RDS master password.
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String
  DatabaseName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The Amazon RDS master database name.
    Type: String
  DatabaseAllocatedStorage:
    Default: '10'
    Description: The size of the database in GiB (ignored if you select a cluster).
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DatabaseSecurityGroup:
    Description: Select the database security group.
    Type: AWS::EC2::SecurityGroup::Id
  DataSubnet0:
    Description: Select an existing database subnet for AZ 0.
    Type: AWS::EC2::Subnet::Id
  DataSubnet1:
    Description: Select an existing database subnet for AZ 1.
    Type: AWS::EC2::Subnet::Id
  DataSubnet2:
    Description: Select an existing database subnet for AZ 2.
    Type: AWS::EC2::Subnet::Id
  MultiAZDatabase:
    AllowedValues:
      - True
      - False
    Default: False
    Description: Specifies whether an RDS instance uses multiple Availability Zones (ignored if you select a cluster).
    Type: String

Conditions:

  MoreThan2AZ:
    !Or [
      !Equals [ !Ref 'AWS::Region', us-east-1 ],
      !Equals [ !Ref 'AWS::Region', us-east-2 ],
      !Equals [ !Ref 'AWS::Region', us-west-2 ],
      !Equals [ !Ref 'AWS::Region', eu-west-1 ],
      !Equals [ !Ref 'AWS::Region', eu-west-2 ],
      !Equals [ !Ref 'AWS::Region', sa-east-1 ],
      !Equals [ !Ref 'AWS::Region', ap-northeast-1 ],
      !Equals [ !Ref 'AWS::Region', ap-southeast-2 ]
    ]

Resources:

  DatabaseCluster:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceClass: !Ref DatabaseInstanceType
      DBName: !Ref DatabaseName
      AllocatedStorage: !Ref DatabaseAllocatedStorage
      Engine: mariadb
      EngineVersion: '10.5'
      MultiAZ: !Ref MultiAZDatabase
      MasterUsername: !Ref DatabaseMasterUsername
      MasterUserPassword: !Ref DatabaseMasterPassword
      VPCSecurityGroups:
      - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 30
      DBSubnetGroupName: !Ref DataSubnetGroup
      Port: 3306
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Drupal / ', !Ref 'AWS::StackName' ] ]
  DataSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Database Subnet Group for Drupal
      SubnetIds:
        !If [
          MoreThan2AZ,
          [ !Ref DataSubnet0, !Ref DataSubnet1, !Ref DataSubnet2 ],
          [ !Ref DataSubnet0, !Ref DataSubnet1 ]
        ]
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Drupal / ', !Ref 'AWS::StackName' ] ]

Outputs:
  DatabaseCluster:
    Value: !Ref DatabaseCluster
  DatabaseName:
    Value: !Ref DatabaseName
  DataSubnetGroup:
    Value: !Ref DataSubnetGroup
  DatabaseClusterEndpointAddress:
    Value: !GetAtt DatabaseCluster.Endpoint.Address

